engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      keyword-spacing:
        enabled: false
ratings:
  paths:
  - www/js
  - www/templates
  - "**.css"
  - "**.js"
  - "**.html"
exclude_paths:
- bower_components/*
- hooks/*
- platforms/*
- node_modules/*
- plugins/*
- resources/*
- www/lib/*
