engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
exclude_paths:
- bower_components/*
- hooks/*
- platforms/*
- node_modules/*
- plugins/*
- resources/*
- www/lib/*
